"""empty message

Revision ID: 264cc6b51f62
Revises: 4b36e4810931
Create Date: 2022-12-29 09:17:50.259351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264cc6b51f62'
down_revision = '4b36e4810931'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('login', sa.VARCHAR(length=70), nullable=True))
    op.add_column('employee', sa.Column('password', sa.VARCHAR(length=70), nullable=True))
    op.create_unique_constraint(op.f('uq__employee__id'), 'employee', ['id'])
    op.create_unique_constraint(op.f('uq__request__id'), 'request', ['id'])
    op.create_unique_constraint(op.f('uq__work_time__id'), 'work_time', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__work_time__id'), 'work_time', type_='unique')
    op.drop_constraint(op.f('uq__request__id'), 'request', type_='unique')
    op.drop_constraint(op.f('uq__employee__id'), 'employee', type_='unique')
    op.drop_column('employee', 'password')
    op.drop_column('employee', 'login')
    # ### end Alembic commands ###
