"""empty message

Revision ID: 4b36e4810931
Revises: f2aa8102c69f
Create Date: 2022-12-14 19:19:34.471066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b36e4810931'
down_revision = 'f2aa8102c69f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=70), nullable=False),
    sa.Column('position', sa.VARCHAR(length=70), nullable=False),
    sa.Column('department', sa.VARCHAR(length=70), nullable=False),
    sa.Column('chief_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__employee')),
    sa.UniqueConstraint('id', name=op.f('uq__employee__id'))
    )
    op.create_table('work_time',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=70), nullable=False),
    sa.Column('work_hours', sa.FLOAT(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__work_time')),
    sa.UniqueConstraint('id', name=op.f('uq__work_time__id'))
    )
    op.create_table('request',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('event', sa.Enum('weekend', 'turnout', 'vacation', 'business_trip', 'sick', 'strike', name='event'), nullable=True),
    sa.Column('from_dt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('to_dt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('status', sa.Enum('ok', 'canceled', 'sent', name='requeststatus'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk__request__employee_id__employee')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__request')),
    sa.UniqueConstraint('id', name=op.f('uq__request__id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    op.drop_table('work_time')
    op.drop_table('employee')
    # ### end Alembic commands ###
